#!/bin/bash
help(){
        cat <<EOF 
        usage: ts_make_tsuser [-p]

        -p /path/to/mountpoint      The directory where the target file system
                                    is mounted. Use this if you are working on
                                    an externally or mounted  drive 

Adds tsuser to a system with root privileges. 
You will need to run ts_revert_passwords when you are finished.
This is considered obsolete. Root the box instead.

EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hp:" option; do
        case $option in
                h) help
                   exit 0
                ;;
                p) path="$OPTARG"
                ;;
                \?) help
                    exit 1
                ;;
        esac
done


if [[ $path ]]; then 
	chroot_path="chroot $path"
fi




# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS
pwhash="zogN6hOIYS8W2"
user="tsuser"
uid="50001"
### MAIN ###
if ! test_for_root; then
        echo "Could not proceed"
        echo "are you root?"
        exit 3
elif ! password_backup=$(backup_passwords_for_reset $path); then
        echo $password_backup
	echo "WARNING:Password files could not be backed up! exiting..."
        exit 3
else
        echo $password_backup
fi

# set uid and gid to something unlikely to be used elsewhere
if ! $chroot_path useradd --create-home --user-group --shell /bin/bash --password "$pwhash" --uid $uid --groups adm --groups admin $user ;then
	echo "WARNING: Could not create user, exiting..."
	exit 3
else	
	echo "user $user has been created with sudo privileges."
	exit 0
fi
