#!/bin/bash
source  /path/to/functions/being/tested
source ./ut_functions
fail_count=0
#### usage #####
# ut.fail                           echo fail and increment fail count
# ut.pass                           echo pass
#ut.test_true [function] [input]    calls ut.pass if function  return 0 
#                                   otherwise ut.fail
#ut.test_false [function] [input]   calls ut.pass if function does notreturn 0 
#                                   otherwise ut.fail
#ut.test_output [function] [input] [expected-output]
#                                   returns 255 if ouput is empty
#                                   1 if input and output do not match
#                                   0 if input and output do match
#                                   it does regex match on [expected-output]
#ut.assert_equals [got] [expected]  calls ut.pass if got == expected otherwise 
#                                   ut.fails. Use like this
#                                   out=$(function) 
#                                   ut.assert_equals $out 'expected'
#                                   returns 0 on match, 1 otherwise.
#ut.assert_matches [got] [expected] as above but does regex match




if (( $fail_count > 254 )); then
    fail_count=255
    echo "Number of failed tests: 255 or greater"
else
    echo "Number of failed tests: $fail_count"
fi
exit $fail_count
