#!/bin/bash
help(){
        cat <<EOF 
        usage: ts_getid [-p]
        
	-p /path/to/mountpoint          The directory where the target file 
                                        system is mounted. Use this if you are
                                        working on an externally mounted drive
                                    

        returns the system id if present.
EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hp:" option; do
        case $option in
                h) help
                   exit 0
                ;;
		p) path="$OPTARG"
                ;;
                \?) help
                    exit 1
                ;;
        esac
done

if [[ -e $path/var/lib/freegeek-extras/printme/system_id ]] 
then 
	echo -n "System ID:"
	cat $path/var/lib/freegeek-extras/printme/system_id 
	exit 0
else 
	echo "system id not found" 
	exit 1
fi


