#!/bin/bash

help(){
	cat <<EOF 
	usage ts_login_as_user [OPTION]
	-h		prints this message
	-u [USERNAME]	specify the user whose password will be changed. 
EOF
	exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

while getopts ":hu:" option; do
	case $option in 
		h) help
		   exit
		;;
		u) user=$OPTARG
		;;
		/?) help
		    exit
		;;
	esac
done

test_for_root
if [[ $? -ne 0 ]]; then
        echo "Could not proceed!"
        echo "are you root?"
        exit 3
fi

backup_passwords
password_backup=$?
if [[ $password_backup -ne 0 ]]; then
	echo $password_backup
        echo "WARNING:Password files could not be backed up! exiting..."
        exit 3
fi

if [[ -z $user ]]; then 
	user=$(choose_username)
fi

test_for_user $user
if (( $? != 0 )); then
        echo "$user not found! exiting..."
        exit 3
fi


password_reset=$(change_password $user)
if [[ password_reset -ne 0 ]]; then
	echo "WARNING:Password could not be reset, exiting..."
	exit 3
else 
	cat <<EOF
password for $user has been set to freegeek. It will revert to the user's original password next time the machine is rebooted or shutdown.

You may mow exit recovery mode and log in as that user.
EOF
	exit 0
fi
