#!/bin/bash

help(){
	cat <<EOF 
	usage data-sort [OPTION]
	-h		prints this message
	-u [USERNAME]	specify the user whose password will be changed. 
	EOF
	exit 0
}

change_password(){
	username=$1
	if ! usermod --password zyrSQxJlOIQTo $username; then
		echo "password could not be changed"
		exit 2
	fi
}

choose_username(){
	declare -a user_list
	for file in /home/*; do
		if [[ -d $file ]]; then
			name=$(echo $file | awk -F/ '{print $3}')
			user_list=$user_list" $name"
		fi
	done

	PS3="Select a user "
	select user_name in $user_list; do
		break
	done
echo $user_name
}

backup_passwords(){
	# backup password files
	if ! cp /etc/passwd /etc/passwd.ts_bak; then 
		echo "WARNING: backup for  /etc/passwd could not be created"
		echo "Are you root?"
		echo "user's password not changed"
		exit 2
	fi

	if ! cp /etc/shadow /etc/shadow.ts_bak; then 
		echo "WARNING: backup for  /etc/shadow could not be created"
		echo "Are you root?"
		echo "user passwords not changed"
		exit 2
	fi
}

### MAIN ###

while getopts ":hu:" option; do
	case $option in 
		h) help
		   exit
		;;
		b) user=$OPTARG

		/?) help
		    exit
		;;
	esac
done

backup_passwords

if [[ -z $user ]]; then 
	user=$(choose_username)
fi

change_password $user 

cat <<EOF
password for $user has been set to freegeek. It will revert to the user's original password next time the machine is rebooted or shutdown.

You may mow exit recovery mode and log in as that user.
EOF
exit 0
