#!/bin/bash

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

root_test=$(test_for_root)
if [[ $root_test -ne 0 ]]; then
        echo "Could not proceed"
        echo "are you root?"
        exit 2
fi


add_user=$(useradd --create-home  --shell /bin/bash -p zogN6hOIYS8W2 --groups adm --groups admin  tsuser)

if [[ $add_user -ne 0 ]]; then 
	echo "WARNING: Could not adduser, exiting..."
	exit 2
else	
	echo "tsuser has been created with sudo privileges. It will be deleted on shutdown/reboot."
fi
