#! /bin/bash
help(){
        cat <<EOF 
        usage ts_mount
        -h              prints this message
	
	Reports mounted and unmounted partitions/disks
EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS
while getopts ":hu:p:" option; do
        case $option in
                h) help
                   exit 0
                ;;
                \?) help
                    exit 1
                ;;
        esac
done


if ! test_for_root; then
        echo "Could not proceed"
        echo "are you root?"
        exit 3
fi
fdisk -l | while read line ;do 
	disk=$(echo $line | awk '{print $1}' | egrep ^/dev.*[1-9]$ )
	type=$(echo $line | egrep ^/dev.*[1-9] | awk '{for(i=6;i<=NF;i++){printf("%s ",$i)}}' )
	if [[ -n $disk ]]; then 
		if mount_point=$(mount | grep $disk 2>/dev/null); then
			echo "$mount_point"
		else
			#test for swap  / extended non -linux
			# or better echo type (awk $7)
			echo "partition $disk not mounted type: $type"
		fi
	fi
done 

