#!/bin/bash

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###
test_for_root
if [[ $? -ne 0 ]]; then
        echo "Could not proceed"
        echo "are you root?"
        exit 3
fi

# set uid and gid to something unlikely to be used elsewhere
add_user=$(useradd --create-home  --shell /bin/bash -p zogN6hOIYS8W2 --uid 5001 --gid 5001 --groups adm --groups admin  tsuser)

if [[ $add_user -ne 0 ]]; then 
	echo "WARNING: Could not adduser, exiting..."
	exit 3
else	
	echo "tsuser has been created with sudo privileges. It will be deleted on shutdown/reboot."
fi
