#!/bin/bash
help(){
	cat <<EOF 
	usage ts_reset_passwd [OPTION]
	-h		prints this message
	-u [USERNAME]	specify the user whose password will be reset. 
	
EOF
	exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

phash="zyrSQxJlOIQTo"

### MAIN ###

while getopts ":hu:" option; do
	case $option in 
		h) help
		   exit
		;;
		u) user=$OPTARG
		;;
		/?) help
		    exit
		;;
	esac
done

if [[ -z $user ]]; then
        user=$(choose_username)
fi


if ! test_for_root; then       
	echo "Could not proceed"
        echo "are you root?"
        exit 3
elif test_for_user $user; then        
	echo "$user not found! exiting..."
        exit 3
fi


if ! reset_password $user "$phash"; then
	echo "password for $user could not be reset"
	exit 3
elif ! expire_password $user; then
	echo "WARNING:Password for $user has been reset to freegeek. It will not expire"
	exit 3
else
	echo "password for $user has been set to freegeek. It will expire on the next login and the user will be prompted to reset it."
	exit 0
fi
