#!/bin/bash
help(){
        cat <<EOF 
        usage ts_ rechown[OPTION]
        -h              prints this message
        -u [USERNAME]   specify the user.
	
	Restores correct ownership  of a users files.
EOF
        exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hu:" option; do
        case $option in
                h) help
                   exit
                ;;
                u) user=$OPTARG
		;;
                /?) help
                    exit
                ;;
        esac
done



test_for_root
if [[ $? -ne 0 ]]; then
        echo "You are not root! exiting..."
        exit 3
fi

test_for_user $user
if (( $? != 0 )); then
        echo "$user not found! exiting..."
        exit 3
fi


      
### reset ownership ###

if ! chown -R $user.$user /home/$user ; then
	echo "WARNING: Failed to change ownership for some or all files!"
	exit 3
else
	echo "Changed ownership of $user's files"
	exit 0
fi
