#!/bin/bash
help(){
        cat <<EOF 
        usage: ts_rechown[OPTION]
        -h                          prints this message
        -u [USERNAME]               specify the user.
        -p /path/to/mountpoint      The directory where the target file system i
                                    is mounted. Use this if you are working on 
                                    an externally mounted  drive 
	
	Restores correct ownership of a users files. Should not be needed when
        using ts_network_backup.
EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hu:p:" option; do
        case $option in
                h) help
                   exit 0
                ;;
                u) user=$OPTARG
		;;
                p) path="$OPTARG"
                ;;
                \?) help
                    exit 1
                ;;
        esac
done




if [[ -z $user ]]; then 
        user=$(choose_username)
fi

if ! test_for_root; then
        echo "You are not root! exiting..."
        exit 3
elif ! test_for_user $user $path; then
        echo "$user not found! exiting..."
        exit 3      
### reset ownership ###
elif ! chown -R $user.$user $path/home/$user ; then
	echo "WARNING: Failed to change ownership for some or all files!"
	exit 3
else
	echo "Changed ownership of $user's files"
	exit 0
fi
