#!/bin/bash
help(){
	cat <<EOF 
	usage data-sort [OPTION]
	-h		prints this message
	-u [USERNAME]	specify the user whose password will be reset. 
	EOF
	exit 0
}

choose_username(){
	declare -a user_list
	for file in /home/*; do
		if [[ -d $file ]]; then
			name=$(echo $file | awk -F/ '{print $3}')
			user_list=$user_list" $name"
		fi
	done

	PS3="Select a user "
	select user_name in $user_list; do
		break
	done
echo $user_name
}

reset_password(){
	user=$1
	if ! usermod --password zyrSQxJlOIQTo $user; then 
		echo "WARNING: user's password not changed"
		echo "Are you root?"
		exit 2
	fi
	if ! passwd -e $user; then 
		echo "WARNING: user's password will not expire automatically"
		EXIT=1
	fi
}

### MAIN ###

while getopts ":hu:" option; do
	case $option in 
		h) help
		   exit
		;;
		b) user=$OPTARG

		/?) help
		    exit
		;;
	esac
done

if [[ -z $user ]]; then 
	user=$(choose_username)
fi

reset_password $user 

cat <<EOF
password for $user has been set to freegeek. 
It will expire on the next login and the user will be prompted to reset it.
EOF

if [[ -z $EXIT ]]; then
	EXIT=0
fi

exit $EXIT
