#!/bin/bash
help(){
        cat <<EOF 
        usage ts_reset_ windowmanger [OPTION]
        -h              prints this message
        -u [USERNAME]   specify the user whose desktop will be reset.
	
	Resets a users desktop/windowmanager to the default settings.
	This will reset ALL of a users desktop settings. Don't use it to reset the panel, use ts_reset_panel. This should only be used if things are really mesesed up.
EOF
        exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### process options ###
while getopts ":hu:" option; do
        case $option in
                h) help
                   exit
                ;;
                u) user=$OPTARG
		;;
                /?) help
                    exit
                ;;
        esac
done

if [[ -z $user ]]; then
        user=$EUID
else
	test_for_user $user
	if (( $? != 0 )); then
        	echo "$user not found! exiting..."
        	exit 3
	fi

	test_for_root
	if [[ $? -ne 0 ]]; then
		echo "You are not root! exiting..."
		exit 3	
		fi
fi

### reset desktop ###

# set appropriate command and options
GCONF_RESET=$(set_gconf $user)

# recursive uset of gnome schemas
for setting in /apps/compiz /apps/metacity /desktop/gnome/session /schemas/desktop/gnome/session
do	
	$GCONF_RESET $setting 
	if [[ $? -ne 0 ]]; then
        	echo "gconf failed to reset $setting" 
        	EXIT=1
	fi
done

if [[ -z  $EXIT ]] ; then
        exit $EXIT
else
        exit 0
fi

