#!/bin/bash
help(){
        cat <<EOF 
        usage: ts_revert_passwords [OPTIONS]

        -p /path/to/mountpoint        The directory where the target file system is mounted. Use this if you are working on an external or mounted  drive e.g. a drive mounted from a system rescue cd.
	-e [extension] 		      The file extension e.g. .freegeek_ts_bak.20110721. The default is .freegeek_ts_bak . For use with backup files ending in an iso date.
 
	Restores the systems original password files, reverting any password changes and removing any added users.

EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hp:e:" option; do
        case $option in
               h) help
                   exit 0
                ;;
                p) path="$OPTARG"
                ;;
		e) extension=$(echo "$OPTARG" | sed s/^\\.//)
		;;
                \?) help
                    exit 1
                ;;
        esac
done

if ! revert_check=$(revert_passwords $path $extension); then
	echo $revert_check
	exit 3
else
        echo $revert_check
        exit 0
fi
