#!/bin/bash
help(){
        cat <<EOF 
        usage: ts_make_tsuser [-p]

        -p /path/to/mountpoint        The directory where the target file system is mounted. Use this if you are working on an external or mounted  drive e.g. a drive mounted from a system rescue cd.

	Restores the systems original password files, reverting any password changes and removing any added users.
EOF
        exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### Process options ###

while getopts ":hp:" option; do
        case $option in
                h) help
                   exit
                ;;
                p) path="$OPTARG"
                ;;
                \?) help
                    exit
                ;;
        esac
done

if ! revert_check=$(revert_passwords $path); then
	echo $revert_check
	exit 3
else
        echo $revert_check
        exit 0
fi

