#!/bin/bash
help(){
        cat <<EOF 
        usage ts_reset_panel [OPTION]
        -h              prints this message
        -u [USERNAME]   specify the user whose panels will be reset,
			defaults to the user running the command.
	Resets gnome panels to their default state. 
EOF
        exit 0
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### process options ###

while getopts ":hu:" option; do
        case $option in
                h) help
                   exit
                ;;
                u) user=$OPTARG
		;;
                /?) help
                    exit
                ;;
        esac
done

#set/check user
if [[ -z $user ]]; then
        user=$EUID
fi

if ! test_for_user $user ; then
        echo "$user not found! exiting..."
        exit 3
elif ! test_for_root; then
	echo "You are not root! exiting..."
	exit 3  
fi


# reset panel second stage maybe unnecessary need to test

# set appropriate command and options
if ! set_gconf $user /apps/panel; then
	echo "gconf failed to reset panel" 
	exit 3

#rm -rf /home/$user/.gconf/apps/panel
#if [[ $? -ne 0 ]]; then
#        echo "gconf failed to reset" 
#        EXIT=1
#fi

elif ! pkill gnome-panel ; then
        echo "failed to restart gnome-panel" 
        exit 3
else
	exit 0
fi
 
