#!/bin/bash

# Functions
help_install(){
		echo "This is just a wrapper around the discspan.py script. For it to work you need to make sure discspan.py has been copied to /usr/local/bin/ and  discspan.ini to /usr/local/etc/ or /etc/. You will need to edit this file to specify the drive speed.

You can download it from Source Forge: 
	http://sourceforge.net/projects/discspan/"
		exit 2
}

check_ini(){
	if [[ -e //usr/local/etc/discpan.ini ]]; then 
		true
	elif [[ /etc/discpan.ini ]]; then
		true 
	else
		help_install
	fi
}

# check to see if files are installed in place.

if [[ ! -e /usr/local/bin/discspan.py ]]; then 
	help_install
	fi

check_ini

# echo warning

cat <<EOF 
This is (a wrapper for) the discspan.py script. It will take the contents of a  directory specified by --dir and burn it to one or more DVD's 
It is fussy about a couple of things. It doesn't always like it when a blank
disc is inserted before it is started and it really doesn't like it if you install a second (or third etc) disc before it is ready. It is not very clear (or at least disarmingly literal)  about the last part.

So when it says "press enter to continue" or some such, just press Enter! It it will prompt you for the disc when it is ready.

Also it is designed for lots of small files and can't cope with files bigger than the disc capacity.

EOF

# do some stuff with getopts to check for --dir or -h and pass stuff onto the script.
